### ISSUE TITLE
Should we enhance user profile service without SSO?

### ISSUE THREAD

**Issue by theckang** [dudash/openshift-microservices#47]
**Discussion Topic / Overview**
Discuss whether to enhance user profile service with or without SSO given the time and effort we have before an Istio workshop.

**Kick it off**
In the workshop, we would like the audience to deploy multiple versions of the user profile service to test traffic routing and other Istio features.  We could update the app-ui to use the user profile service as-is, but it would mean using a "fake" user in the flow (currently "anonymous").

We could instead try to get SSO working in the app, but it would block this effort until SSO works.

**Comment by dudash** [comment]
I think a fake user is cool as long as it's easy to configure away when SSO is available.

**Comment by dudash** [comment]
Added a fake user for the default scenario - will plan to move this to a configurable env variable.

https://github.com/dudash/openshift-microservices/blob/fecec06174d2476f262e59978e8f455ca6561244/code/app-ui/routes/profile.js#L13

**Comment by dudash** [comment]
Thinking about this a little more - SSO is the "owner" of user accounts. User profile is just "additional data" related to a specific user account. So the assumption is that a user account must exist to get data from the profile service. But the questions unclear to me are: 
1) when do we create the user in the profile service?
   - first profile request
   - as part of user creation flow

2) what do we do if a user profile doesn't exist and should exist because they exist in SSO
   - ?

3) does the user profile service currently talk with SSO, do it need to talk with SSO?
   - not currently and most likely yes it does

4) best way to fake a user when SSO isn't available?
   - all in app_ui, has "too fake" of a flow because there is no actual REST call between app_ui and profile servier
   - alt: set FAKE_USERS env var in the app_ui, send a magic-number user id in REST call when FAKE_USERS is set, user_profile service knows how to respond to a request for the magic-number user

**Assumptions:**
* when running 2 versions of the profile service, we still have just one backend database service, and both connect into it
* faking a user happens when SSO is unavailable but app_ui and user_profile are

**Comment by dudash** [comment]
the current code has app_ui making requests to the profile service always:
https://github.com/dudash/openshift-microservices/blob/master/code/app-ui/routes/profile.js#L12

The current profile service returns an error for not found and a fake profile when using the MAGIC NUMBER of `575ddb6a-8d2f-4baf-9e7e-4d0184d69259`
